# Generated by Django 6.0.2 on 2026-07-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_add_lat_lng_to_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='agreement_policy',
            field=models.TextField(blank=True, default=''),
        ),
    ]
