# Generated by Django 6.0.2 on 2026-07-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_room_agreement_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='additional_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='room',
            name='fixed_duration_type',
            field=models.CharField(blank=True, default='months', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='fixed_duration_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='house_rules',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='room',
            name='increase_by',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='increment_every',
            field=models.CharField(blank=True, default='monthly', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='increment_type',
            field=models.CharField(blank=True, default='fixed_amount', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='initial_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='rent_mode',
            field=models.CharField(default='fixed', max_length=20),
        ),
    ]
