name: room_rental_system
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  dio: ^5.9.2
  get_storage: ^2.1.1
  image_picker: ^1.0.8
  intl: ^0.19.0
  geolocator: ^14.0.3
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/onboard_screen1.png
    - assets/images/onboard_screen2.png
    - assets/images/onboard_screen3.png
    - assets/images/app_icon.png
    - assets/images/splash_screen.png

flutter_launcher_icons:
  android: true
  ios: true

  image_path: "assets/images/app_icon.png"

  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon.png"

  remove_alpha_ios: true