# Generated by Django 6.0.2 on 2026-05-31 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_maintenancerequest_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance/images/'),
        ),
    ]
