import 'package:flutter/material.dart';
import 'package:get/get.dart';
import '../../controllers/booking_controller.dart';
import 'customer_details_view.dart';

class LandlordRequestsView extends StatelessWidget {
  const LandlordRequestsView({super.key});

  @override
  Widget build(BuildContext context) {
    // Sharing the BookingController instance to see dummy requests generated by tenant
    final BookingController bookingCtrl = Get.put(BookingController());

    return SafeArea(
      child: Scaffold(
        backgroundColor: const Color(0xFFF8F9FB),
        body: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Text("Inbox & Requests", style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold)),
              const SizedBox(height: 16),
              Expanded(
                child: Obx(() {
                  if (bookingCtrl.bookings.isEmpty) {
                    return const Center(child: Text("No booking requests yet."));
                  }
                  
                  return ListView.builder(
                    itemCount: bookingCtrl.bookings.length,
                    itemBuilder: (context, index) {
                      final req = bookingCtrl.bookings[index];
                      // Observe the individual request status changes
                      return Card(
                        margin: const EdgeInsets.only(bottom: 12),
                        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                        // Elevation based on status
                        elevation: 0,
                        child: Container(
                          decoration: BoxDecoration(
                            border: Border.all(color: Colors.grey.shade200),
                            borderRadius: BorderRadius.circular(12),
                          ),
                          child: Padding(
                            padding: const EdgeInsets.all(16.0),
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Row(
                                  children: [
                                    const CircleAvatar(
                                      backgroundColor: Colors.blueAccent,
                                      child: Icon(Icons.person, color: Colors.white),
                                    ),
                                    const SizedBox(width: 12),
                                    Expanded(
                                      child: Column(
                                        crossAxisAlignment: CrossAxisAlignment.start,
                                        children: [
                                          Text(req.userName, style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
                                          Text(req.userPhone, style: TextStyle(color: Colors.grey.shade600, fontSize: 13)),
                                        ],
                                      ),
                                    ),
                                    Obx(() { 
                                       Color statusColor;
                                       if(req.status.value == 'Approved') statusColor = Colors.green;
                                       else if(req.status.value == 'Rejected') statusColor = Colors.red;
                                       else statusColor = Colors.orange;

                                       return Container(
                                          padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                                          decoration: BoxDecoration(
                                            color: statusColor.withOpacity(0.1),
                                            borderRadius: BorderRadius.circular(20),
                                            border: Border.all(color: statusColor.withOpacity(0.5)),
                                          ),
                                          child: Text(
                                            req.status.value,
                                            style: TextStyle(color: statusColor, fontWeight: FontWeight.bold, fontSize: 12),
                                          ),
                                      );
                                    }),
                                  ],
                                ),
                                const Divider(height: 24),
                                Row(
                                  children: [
                                    const Icon(Icons.home, size: 18, color: Colors.grey),
                                    const SizedBox(width: 6),
                                    Expanded(child: Text(req.room?.title ?? 'Unknown Room', style: const TextStyle(fontWeight: FontWeight.w600))),
                                  ],
                                ),
                                const SizedBox(height: 6),
                                Row(
                                  children: [
                                    const Icon(Icons.location_on, size: 18, color: Colors.grey),
                                    const SizedBox(width: 6),
                                    Expanded(child: Text(req.userAddress, style: const TextStyle(color: Colors.grey))),
                                  ],
                                ),
                                const SizedBox(height: 16),
                                Obx(() {
                                  if (req.status.value == 'Pending') {
                                    return Row(
                                      children: [
                                        Expanded(
                                          child: OutlinedButton(
                                            onPressed: () => bookingCtrl.rejectRequest(req.id),
                                            style: OutlinedButton.styleFrom(
                                              foregroundColor: Colors.red,
                                              side: const BorderSide(color: Colors.red),
                                              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                                            ),
                                            child: const Text("Reject"),
                                          ),
                                        ),
                                        const SizedBox(width: 12),
                                        Expanded(
                                          child: ElevatedButton(
                                            onPressed: () => bookingCtrl.approveRequest(req.id),
                                            style: ElevatedButton.styleFrom(
                                              backgroundColor: Colors.teal,
                                              foregroundColor: Colors.white,
                                              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                                            ),
                                            child: const Text("Approve"),
                                          ),
                                        ),
                                      ],
                                    );
                                  } else {
                                    // if approved or rejected, hide actions or show Details button
                                    return SizedBox(
                                      width: double.infinity,
                                      child: ElevatedButton(
                                        onPressed: () => Get.to(() => const CustomerDetailsView()),
                                        style: ElevatedButton.styleFrom(
                                          backgroundColor: Colors.grey.shade100,
                                          foregroundColor: Colors.black87,
                                          elevation: 0,
                                          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                                        ),
                                        child: const Text("View Details"),
                                      ),
                                    );
                                  }
                                }),
                              ],
                            ),
                          ),
                        ),
                      );
                    },
                  );
                }),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
