# Generated by Django 6.0.2 on 2026-05-31 07:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agreement',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
