# Generated by Django 6.0.2 on 2026-06-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_created_at_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_gateway',
            field=models.CharField(choices=[('khalti', 'Khalti'), ('esewa', 'eSewa'), ('manual', 'Manual')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
