# Generated by Django 6.0.2 on 2026-07-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_rentrecord_delete_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentrecord',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('overdue', 'Overdue'), ('pending', 'Pending Verification')], default='unpaid', max_length=20),
        ),
    ]
