# Generated by Django 6.0.2 on 2026-07-11 05:36

from django.db import migrations


def verify_existing_users(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')
    CustomUser.objects.all().update(is_email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_is_email_verified'),
    ]

    operations = [
        migrations.RunPython(verify_existing_users),
    ]
