// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3GniSxeACF9jEtPapeRVCIfk-eByZQlo',
    appId: '1:541399383994:web:2b6eb276bb445def96a783',
    messagingSenderId: '541399383994',
    projectId: 'room-rental-system-1d899',
    authDomain: 'room-rental-system-1d899.firebaseapp.com',
    storageBucket: 'room-rental-system-1d899.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD26NVvjY9s1e9YKBSWTn5Ul88J8zq5rfs',
    appId: '1:541399383994:ios:158528d000c8c27a96a783',
    messagingSenderId: '541399383994',
    projectId: 'room-rental-system-1d899',
    storageBucket: 'room-rental-system-1d899.firebasestorage.app',
    iosBundleId: 'com.example.roomRentalSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3GniSxeACF9jEtPapeRVCIfk-eByZQlo',
    appId: '1:541399383994:web:e5bf7bdf17e6808c96a783',
    messagingSenderId: '541399383994',
    projectId: 'room-rental-system-1d899',
    authDomain: 'room-rental-system-1d899.firebaseapp.com',
    storageBucket: 'room-rental-system-1d899.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbck990SfK1-bRfz_5Ti_7wxMf2jOZf2I',
    appId: '1:541399383994:android:3c83b7796f413da196a783',
    messagingSenderId: '541399383994',
    projectId: 'room-rental-system-1d899',
    storageBucket: 'room-rental-system-1d899.firebasestorage.app',
  );
}
