# Generated by Django 6.0.2 on 2026-07-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_created_at_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rent_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
