# Generated by Django 6.0.2 on 2026-07-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_rent_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
